import type { Metadata } from "next";
import { Oswald as OswaldFont } from "next/font/google";
import "./globals.css";

// Configure the Oswald font
const oswald = OswaldFont({
  subsets: ["latin"],
  weight: ["700","200","300","400","500","600"], // Use `weights` to specify multiple font weights
});
export const metadata: Metadata = {
  title: "Eivent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>{children}</body>
    </html>
  );
}
